# Generated by Django 3.2.4 on 2021-06-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210630_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='commnet',
            field=models.TextField(null=True),
        ),
    ]
