# Generated by Django 3.2.4 on 2021-06-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_commnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='commnet',
        ),
    ]
