# Generated by Django 3.2.4 on 2021-06-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210628_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='explain',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
