# Generated by Django 3.2.4 on 2021-06-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='explain',
            field=models.TextField(null=True),
        ),
    ]
