# Generated by Django 3.2.4 on 2021-06-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_explain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='othercomment',
            field=models.TextField(null=True),
        ),
    ]
