# Generated by Django 3.2.4 on 2021-06-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_othercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Qnum',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
